version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "20:00"
    reviewers:
      - "freitzzz"
      - "rutesantos4"
    commit-message:
      prefix: "bump"
      include: "scope"